const Razorpay = require("razorpay");

exports.corsOptions = {
  origin: ["http://192.168.0.113:8000", "http://localhost:8000"],
  credentials: true,
  optionsSuccessStatus: 200,
};

exports.options = {
  httpOnly: true,
  secure: true,
  sameSite: "None",
};

exports.razorpay = new Razorpay({
  key_id: process.env.RAZOR_PAY_ID,
  key_secret: process.env.RAZOR_PAY_SECRET,
});

exports.Data_for_contests = [
  {
    prize: 250,
    participants: 250,
    ticket_prize: 0,
    patterns: [
      { pattern: "Full Housie", prize: 100 },
      { pattern: "First Line", prize: 50 },
      { pattern: "Middle Line", prize: 50 },
      { pattern: "Last Line", prize: 50 },
    ],
  },
  {
    prize: 150000,
    participants: 4000,
    ticket_prize: 50,
    patterns: [
      { pattern: "Full Housie", prize: 75000 },
      { pattern: "First Line", prize: 10000 },
      { pattern: "Middle Line", prize: 10000 },
      { pattern: "Last Line", prize: 10000 },
      { pattern: "Twin Lines (1 & 2)", prize: 3000 },
      { pattern: "Twin Lines (2 & 3)", prize: 3000 },
      { pattern: "Twin Lines (3 & 1)", prize: 3000 },
      { pattern: "Early Five", prize: 1000 },
      { pattern: "Early Ten", prize: 2000 },
      { pattern: "Pyramid", prize: 2000 },
      { pattern: "Reverse Pyramid", prize: 2000 },
      { pattern: "Corner", prize: 1000 },
      { pattern: "143 (I love You)", prize: 2000 },
      { pattern: "Anda-Danda", prize: 2000 },
      { pattern: "Odd Number", prize: 2000 },
      { pattern: "Even Number", prize: 2000 },
      { pattern: "1 from Each Line", prize: 2000 },
      { pattern: "Smallest Five", prize: 2000 },
      { pattern: "Bigger Five", prize: 2000 },
      { pattern: "1 Balance in Full Housei", prize: 14000 },
    ],
  },
  {
    prize: 100000,
    participants: 30,
    ticket_prize: 5000,
    patterns: [
      { pattern: "Full Housie", prize: 50000 },
      { pattern: "First Line", prize: 10000 },
      { pattern: "Middle Line", prize: 10000 },
      { pattern: "Last Line", prize: 10000 },
      { pattern: "Early Five", prize: 10000 },
      { pattern: "Early Ten", prize: 10000 },
    ],
  },
  {
    prize: 950,
    participants: 30,
    ticket_prize: 50,
    patterns: [
      { pattern: "Full Housie", prize: 400 },
      { pattern: "First Line", prize: 100 },
      { pattern: "Middle Line", prize: 100 },
      { pattern: "Last Line", prize: 100 },
      { pattern: "Corner", prize: 75 },
      { pattern: "Early Five", prize: 75 },
      { pattern: "Odd Number", prize: 50 },
      { pattern: "Even Number", prize: 50 },
    ],
  },
  {
    prize: 38000,
    participants: 2000,
    ticket_prize: 30,
    patterns: [
      { pattern: "Full Housie", prize: 15000 },
      { pattern: "First Line", prize: 3000 },
      { pattern: "Middle Line", prize: 3000 },
      { pattern: "Last Line", prize: 3000 },
      { pattern: "Twin Lines (1 & 2)", prize: 1000 },
      { pattern: "Twin Lines (2 & 3)", prize: 1000 },
      { pattern: "Twin Lines (3 & 1)", prize: 1000 },
      { pattern: "Early Five", prize: 500 },
      { pattern: "Early Ten", prize: 1000 },
      { pattern: "Pyramid", prize: 500 },
      { pattern: "Reverse Pyramid", prize: 500 },
      { pattern: "143 (I love You)", prize: 500 },
      { pattern: "Anda-Danda", prize: 500 },
      { pattern: "Odd Number", prize: 500 },
      { pattern: "Even Number", prize: 500 },
      { pattern: "1 from Each Line", prize: 500 },
      { pattern: "Smallest Five", prize: 500 },
      { pattern: "Bigger Five", prize: 500 },
      { pattern: "1 Balance in Full Housei", prize: 5000 },
    ],
  },
  {
    prize: 31000,
    participants: 50,
    ticket_prize: 1000,
    patterns: [
      { pattern: "Full Housie", prize: 10000 },
      { pattern: "First Line", prize: 4000 },
      { pattern: "Middle Line", prize: 4000 },
      { pattern: "Last Line", prize: 4000 },
      { pattern: "Twin Lines (1 & 2)", prize: 1500 },
      { pattern: "Twin Lines (2 & 3)", prize: 1500 },
      { pattern: "Twin Lines (3 & 1)", prize: 1500 },
      { pattern: "Early Five", prize: 2000 },
      { pattern: "Early Ten", prize: 2500 },
    ],
  },
  {
    prize: 145000,
    participants: 20,
    ticket_prize: 10000,
    patterns: [
      { pattern: "Full Housie", prize: 40000 },
      { pattern: "First Line", prize: 20000 },
      { pattern: "Middle Line", prize: 20000 },
      { pattern: "Last Line", prize: 20000 },
      { pattern: "Twin Lines", prize: 15000 },
      { pattern: "Early Five", prize: 15000 },
      { pattern: "Early Ten", prize: 15000 },
    ],
  },
  {
    prize: 270000,
    participants: 15,
    ticket_prize: 25000,
    patterns: [
      { pattern: "Full Housie", prize: 120000 },
      { pattern: "First Line", prize: 50000 },
      { pattern: "Middle Line", prize: 50000 },
      { pattern: "Last Line", prize: 50000 },
    ],
  },
  {
    prize: 139000,
    participants: 10000,
    ticket_prize: 20,
    patterns: [
      { pattern: "Full Housie", prize: 50000 },
      { pattern: "First Line", prize: 4000 },
      { pattern: "Middle Line", prize: 4000 },
      { pattern: "Last Line", prize: 4000 },
      { pattern: "Twin Lines (1 & 2)", prize: 1500 },
      { pattern: "Twin Lines (2 & 3)", prize: 1500 },
      { pattern: "Twin Lines (3 & 1)", prize: 1500 },
      { pattern: "Early Five", prize: 500 },
      { pattern: "Early Ten", prize: 1000 },
      { pattern: "Pyramid", prize: 1000 },
      { pattern: "Reverse Pyramid", prize: 1000 },
      { pattern: "Corner", prize: 1000 },
      { pattern: "143 (I love You)", prize: 3000 },
      { pattern: "Anda-Danda", prize: 3000 },
      { pattern: "Odd Number", prize: 3000 },
      { pattern: "Even Number", prize: 3000 },
      { pattern: "1 from Each Line", prize: 3000 },
      { pattern: "Smallest Five", prize: 3000 },
      { pattern: "Bigger Five", prize: 3000 },
      { pattern: "Above 50 (Young)", prize: 3000 },
      { pattern: "Below 50 (Old)", prize: 3000 },
      { pattern: "T", prize: 3000 },
      { pattern: "H", prize: 3000 },
      {
        pattern: "1 Balance in Full Housei",
        prize: 25000,
      },
      {
        pattern: "2 Balance in Full Housei",
        prize: 10000,
      },
    ],
  },
  {
    prize: 1100,
    participants: 100,
    ticket_prize: 20,
    patterns: [
      { pattern: "Full Housie", prize: 500 },
      { pattern: "First Line", prize: 100 },
      { pattern: "Middle Line", prize: 100 },
      { pattern: "Last Line", prize: 100 },
      { pattern: "Twin Lines", prize: 200 },
      { pattern: "Early Five", prize: 50 },
      { pattern: "Early Ten", prize: 50 },
    ],
  },
  {
    prize: 3400000,
    participants: 100000,
    ticket_prize: 49,
    patterns: [
      { pattern: "Full Housie", prize: 2500000 },
      { pattern: "First Line", prize: 50000 },
      { pattern: "Middle Line", prize: 50000 },
      { pattern: "Last Line", prize: 50000 },
      { pattern: "Twin Lines (1 & 2)", prize: 25000 },
      { pattern: "Twin Lines (2 & 3)", prize: 25000 },
      { pattern: "Twin Lines (3 & 1)", prize: 25000 },
      { pattern: "Early Five", prize: 10000 },
      { pattern: "Early Ten", prize: 15000 },
      { pattern: "143 (I love You)", prize: 7500 },
      { pattern: "Anda-Danda", prize: 7500 },
      { pattern: "Odd Number", prize: 7500 },
      { pattern: "Even Number", prize: 7500 },
      { pattern: "1 from Each Line", prize: 7500 },
      { pattern: "Smallest Five", prize: 7500 },
      { pattern: "Bigger Five", prize: 7500 },
      { pattern: "Unlucky 1 (in First 10 number)", prize: 7500 },
      { pattern: "Above 50", prize: 7500 },
      { pattern: "Below 50", prize: 7500 },
      { pattern: "T", prize: 7500 },
      { pattern: "H", prize: 7500 },
      { pattern: "1 Balance in Full Housei", prize: 350000 },
      { pattern: "2 Balance in Full Housei", prize: 210000 },
    ],
  },
];

exports.numberRanges = [
  [1, 9],
  [10, 19],
  [20, 29],
  [30, 39],
  [40, 49],
  [50, 59],
  [60, 69],
  [70, 79],
  [80, 90],
];
